/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
    kotlin("plugin.serialization") version "1.8.22"
}

repositories {
    mavenCentral()
    maven("https://papermc.io/repo/repository/maven-public/") // Paper API
}

dependencies {
    implementation("org.apache.commons:commons-text")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    compileOnly("io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT") // Paper API

    implementation("io.ktor:ktor-server-core:2.3.2")
    implementation("io.ktor:ktor-server-netty:2.3.2")
    implementation("io.ktor:ktor-server-content-negotiation:2.3.2")
    implementation("io.ktor:ktor-serialization-kotlinx-json:2.3.2")
    implementation("io.ktor:ktor-client-websockets:2.3.0")
    implementation("io.ktor:ktor-client-cio:2.3.0")
}

application {
    // Define the main class for the application.
    mainClass = "com.chanwook.app.Ktulu"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
